import os
from anthropic import Anthropic
from dotenv import load_dotenv

# Load the API key from .env file
load_dotenv()

# Create the client — this is the object we use to talk to the API
client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def analyze_sensor_data(sensor_readings: dict) -> str:
    """
    Takes sensor readings from an industrial unit
    and returns a risk analysis in natural language.
    
    Args:
        sensor_readings: dict of sensor names and their current values
    Returns:
        str: risk analysis generated by the LLM
    """
    
    # Build the API call with a specialized system prompt
    message = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=500,
        # System prompt defines the role and expertise of the AI
        system="""You are an expert in industrial predictive maintenance 
        with 15 years of experience analyzing turbofan engine sensor data.
        You identify failure risks and recommend concrete actions.
        Always respond in English.""",
        messages=[
            {
                "role": "user",
                # Inject the sensor data directly into the prompt
                "content": f"Analyze these sensor readings and assess failure risk: {sensor_readings}"
            }
        ]
    )
    
    # The response is always in content[0].text
    return message.content[0].text

# Test the function with real data from our CMAPSS exploration
if __name__ == "__main__":
    
    # Sample sensor readings from unit 1, cycle 180 (near end of life)
    test_sensors = {
        "sensor_2": 642.83,
        "sensor_3": 1590.52,
        "sensor_4": 1408.93,
        "sensor_7": 554.37,
        "sensor_9": 9065.25,
        "sensor_11": 47.91,
        "sensor_12": 521.72,
        "sensor_14": 8138.62,
        "sensor_17": 393,
        "sensor_20": 39.06,
        "sensor_21": 23.42
    }
    
    print("Sending sensor data to the API...")
    result = analyze_sensor_data(test_sensors)
    print(result)